# Generated by Django 6.1.1 on 2026-09-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='closing_time',
            field=models.TimeField(blank=True, null=True, verbose_name='ساعت پایان کار'),
        ),
        migrations.AddField(
            model_name='business',
            name='opening_time',
            field=models.TimeField(blank=True, null=True, verbose_name='ساعت شروع کار'),
        ),
    ]
