# Generated by Django 6.1.1 on 2026-09-25 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_business_closing_time_business_opening_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessWorkingHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'شنبه'), (1, 'یکشنبه'), (2, 'دوشنبه'), (3, 'سه\u200cشنبه'), (4, 'چهارشنبه'), (5, 'پنجشنبه'), (6, 'جمعه')], verbose_name='روز هفته')),
                ('is_closed', models.BooleanField(default=False, verbose_name='تعطیل')),
                ('opening_time', models.TimeField(blank=True, null=True, verbose_name='ساعت شروع')),
                ('closing_time', models.TimeField(blank=True, null=True, verbose_name='ساعت پایان')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='booking.business', verbose_name='کسب\u200cوکار')),
            ],
            options={
                'verbose_name': 'ساعت کاری',
                'verbose_name_plural': 'ساعات کاری',
                'ordering': ['weekday'],
            },
        ),
    ]
