# Generated by Django 6.1.1 on 2026-09-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='businesses/', verbose_name='تصویر کسب\u200cوکار'),
        ),
    ]
